language: php

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

stages:
  - static_analysis
  - test

.Functional Tests Template: &functional_tests
  stage: test
  service:
    - mysql
  install:
    - composer require typo3/minimal="$TYPO3_VERSION"
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;
    - export TYPO3_PATH_ROOT=$PWD/.Build/public
    - export typo3DatabaseName=typo3
    - export typo3DatabaseHost=localhost
    - export typo3DatabaseUsername=root
    - export typo3DatabasePassword=
  script:
    - php .Build/bin/phpunit -c ./phpunit.xml --coverage-clover=coverage.xml
    - bash <(curl -s https://codecov.io/bash)

.Lint PHP: &lint_php
  stage: static_analysis
  script:
    - find . -name \*.php ! -path "./.Build/*" ! -path "./vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;

.Lint Editorconfig: &editor_config
  stage: static_analysis
  install:
    - npm install -g editorconfig-checker@^2.0
  script:
    - editorconfig-checker -exclude '(LICENSE|^Documentation/)'

.PHPStan: &php_stan
  stage: static_analysis
  install:
    - composer install --prefer-dist --no-progress
  script:
    - php .Build/bin/phpstan analyse

jobs:
  include:
    - <<: *lint_php
      name: Lint PHP 7.4
      php: 7.4
    - <<: *lint_php
      name: Lint PHP 7.3
      php: 7.3
    - <<: *lint_php
      name: Lint PHP 7.2
      php: 7.2
    - <<: *editor_config
      name: Lint Editorconfig
    - <<: *php_stan
      name: PHPStan (PHP 7.4)
      php: 7.4
    - <<: *php_stan
      name: PHPStan (PHP 7.3)
      php: 7.3
    - <<: *php_stan
      name: PHPStan (PHP 7.2)
      php: 7.2
    - <<: *functional_tests
      name: Functional Tests (TYPO3 9.5, PHP 7.4)
      php: 7.4
      env: TYPO3_VERSION=^9.5
    - <<: *functional_tests
      name: Functional Tests (TYPO3 9.5, PHP 7.3)
      php: 7.3
      env: TYPO3_VERSION=^9.5
    - <<: *functional_tests
      name: Functional Tests (TYPO3 9.5, PHP 7.2)
      php: 7.2
      env: TYPO3_VERSION=^9.5
    - <<: *functional_tests
      name: Functional Tests with lowest dependencies (TYPO3 9.5, PHP 7.2)
      php: 7.2
      env:
        - dependencies=lowest
        - TYPO3_VERSION=^9.5
    - <<: *functional_tests
      name: Functional Tests (TYPO3 10.3, PHP 7.4)
      php: 7.4
      env: TYPO3_VERSION=^10.3
    - <<: *functional_tests
      name: Functional Tests (TYPO3 10.3, PHP 7.3)
      php: 7.3
      env: TYPO3_VERSION=^10.3
    - <<: *functional_tests
      name: Functional Tests (TYPO3 10.3, PHP 7.2)
      php: 7.2
      env: TYPO3_VERSION=^10.3
